export const LEARNING_CONFIG = {
  ACTIVE_POOL_SIZE: 10,
  REQUIRED_STREAK_PER_DIRECTION: 1,
  FIRST_REST_DELAY_HOURS: 3,
  SECOND_REST_DELAY_HOURS: 12,
  FIRST_LONG_REVIEW_DAYS: 7,
  SECOND_LONG_REVIEW_DAYS: 30,
} as const;

export type LearningConfig = typeof LEARNING_CONFIG;
